"""
Base helpers for AutoNegocio AI agents.

Every agent works without an API key (deterministic, data-driven logic) and,
when ANTHROPIC_API_KEY is set, adds a written analysis generated by Claude.
"""

import logging
from typing import Optional

from backend.config.settings import settings

logger = logging.getLogger(__name__)

_client = None


def ia_disponible() -> bool:
    """True when Claude can be used (API key configured and SDK installed)."""
    if not settings.ANTHROPIC_API_KEY:
        return False
    try:
        import anthropic  # noqa: F401
    except ImportError:
        return False
    return True


def _get_client():
    global _client
    if _client is None and ia_disponible():
        import anthropic

        _client = anthropic.AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)
    return _client


async def ask_claude(prompt: str, system: str = "", max_tokens: int = 8000) -> Optional[str]:
    """
    Send a prompt to Claude and return the text of the answer, or None when
    the API is not configured or the call fails (callers then use their
    deterministic fallback).
    """
    client = _get_client()
    if client is None:
        return None

    import anthropic

    kwargs = {
        "model": settings.CLAUDE_MODEL,
        # Thinking is always on in current models and counts toward max_tokens
        "max_tokens": max(max_tokens, 8000),
        "messages": [{"role": "user", "content": prompt}],
        # Short business analyses: medium effort is enough
        "output_config": {"effort": "medium"},
        # If a safety classifier declines, the API retries on a fallback model
        "betas": ["server-side-fallback-2026-07-01"],
        "fallbacks": "default",
    }
    if system:
        kwargs["system"] = system

    try:
        response = await client.beta.messages.create(**kwargs)
    except anthropic.AuthenticationError:
        logger.error("ANTHROPIC_API_KEY inválida — los agentes usan su lógica propia")
        return None
    except anthropic.RateLimitError:
        logger.warning("Límite de uso de Claude alcanzado — se usa la lógica propia")
        return None
    except anthropic.APIStatusError as exc:
        logger.error("Error de la API de Claude (%s): %s", exc.status_code, exc.message)
        return None
    except anthropic.APIConnectionError as exc:
        logger.error("No se pudo conectar con Claude: %s", exc)
        return None

    if response.stop_reason == "refusal":
        logger.warning("Claude declinó la solicitud: %s", getattr(response, "stop_details", None))
        return None
    # The answer may start with (empty) thinking blocks: keep only the text
    text = "".join(block.text for block in response.content if block.type == "text").strip()
    return text or None
