export interface Vehicle {
  id: number;
  marca: string;
  modelo: string;
  anio: number;
  precio: number;
  precio_compra?: number;
  kilometraje: number;
  transmision: 'Automática' | 'Manual';
  combustible: 'Gasolina' | 'Diésel' | 'Híbrido' | 'Eléctrico';
  tipo: 'SUV' | 'Sedán' | 'Hatchback' | 'Pickup' | 'Van';
  color: string;
  ubicacion: string;
  estado: 'Disponible' | 'Reservado' | 'Vendido';
  imagen: string;
  descripcion: string;
  soat: boolean;
  tecnicomecanica: boolean;
  impuestos: boolean;
  dias_inventario?: number;
}

export const vehiculosPlaceholder: Vehicle[] = [
  {
    id: 1,
    marca: 'Mazda',
    modelo: 'CX-5 Grand Touring',
    anio: 2023,
    precio: 145000000,
    precio_compra: 128000000,
    kilometraje: 15000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Rojo Cristal',
    ubicacion: 'Bogotá - Chapinero',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Mazda CX-5 Grand Touring en excelente estado. Único dueño, todos los mantenimientos en concesionario. Techo panorámico, cuero, sensores de parqueo, cámara de reversa.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 12,
  },
  {
    id: 2,
    marca: 'Toyota',
    modelo: 'Fortuner 2.7L',
    anio: 2022,
    precio: 185000000,
    precio_compra: 162000000,
    kilometraje: 32000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Blanco Perlado',
    ubicacion: 'Bogotá - Usaquén',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Toyota Fortuner en perfecto estado mecánico y estético. Segundo dueño, vidrios blindados nivel 2. Ideal para familia.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 8,
  },
  {
    id: 3,
    marca: 'Chevrolet',
    modelo: 'Tracker LT',
    anio: 2024,
    precio: 98000000,
    precio_compra: 85000000,
    kilometraje: 5200,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Gris Oscuro',
    ubicacion: 'Bogotá - Suba',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Chevrolet Tracker último modelo, prácticamente nueva. Apple CarPlay, Android Auto, asistente de frenado. Garantía de fábrica vigente.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 5,
  },
  {
    id: 4,
    marca: 'Kia',
    modelo: 'Sportage EX',
    anio: 2023,
    precio: 128000000,
    precio_compra: 112000000,
    kilometraje: 18500,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Negro',
    ubicacion: 'Bogotá - Cedritos',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Kia Sportage nueva generación. Diseño renovado, pantalla dual, asientos en cuero sintético, sistema de navegación. Impecable.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 15,
  },
  {
    id: 5,
    marca: 'Renault',
    modelo: 'Duster Intens',
    anio: 2023,
    precio: 78000000,
    precio_compra: 67000000,
    kilometraje: 22000,
    transmision: 'Manual',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Azul',
    ubicacion: 'Bogotá - Kennedy',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Renault Duster versión Intens con multimedia, cámara de reversa, control crucero. Excelente relación calidad-precio.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 20,
  },
  {
    id: 6,
    marca: 'Hyundai',
    modelo: 'Tucson Limited',
    anio: 2022,
    precio: 138000000,
    precio_compra: 120000000,
    kilometraje: 28000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Plata',
    ubicacion: 'Bogotá - Calle 170',
    estado: 'Reservado',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Hyundai Tucson versión full equipo. Techo panorámico, asientos ventilados, sistema Bluelink, cargador inalámbrico.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 3,
  },
  {
    id: 7,
    marca: 'Mazda',
    modelo: '3 Sedán Touring',
    anio: 2023,
    precio: 95000000,
    precio_compra: 82000000,
    kilometraje: 12000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'Sedán',
    color: 'Blanco Nieve',
    ubicacion: 'Bogotá - Chicó',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Mazda 3 con el reconocido motor Skyactiv. Interior premium, excelente consumo de combustible, todos los sistemas de seguridad activos.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 10,
  },
  {
    id: 8,
    marca: 'Toyota',
    modelo: 'Corolla SEG Hybrid',
    anio: 2024,
    precio: 135000000,
    precio_compra: 118000000,
    kilometraje: 3800,
    transmision: 'Automática',
    combustible: 'Híbrido',
    tipo: 'Sedán',
    color: 'Gris Metálico',
    ubicacion: 'Bogotá - Autopista Norte',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Toyota Corolla Hybrid última generación. Consumo excepcional, Toyota Safety Sense completo, pantalla 10.5 pulgadas.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 7,
  },
  {
    id: 9,
    marca: 'Chevrolet',
    modelo: 'Onix Turbo Premier',
    anio: 2023,
    precio: 72000000,
    precio_compra: 62000000,
    kilometraje: 19000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'Sedán',
    color: 'Rojo',
    ubicacion: 'Bogotá - Fontibón',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Chevrolet Onix Turbo versión Premier. Motor 1.0 turbo eficiente, Wi-Fi integrado, 6 airbags, control de estabilidad.',
    soat: true,
    tecnicomecanica: false,
    impuestos: true,
    dias_inventario: 25,
  },
  {
    id: 10,
    marca: 'Kia',
    modelo: 'Seltos Zenith',
    anio: 2023,
    precio: 108000000,
    precio_compra: 94000000,
    kilometraje: 14500,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Verde Oliva',
    ubicacion: 'Bogotá - Calle 80',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Kia Seltos versión tope de línea. Sistema UVO, pantalla 10.25", sistema de sonido Bose, asistente de punto ciego.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 14,
  },
  {
    id: 11,
    marca: 'Renault',
    modelo: 'Koleos Intens',
    anio: 2022,
    precio: 118000000,
    precio_compra: 102000000,
    kilometraje: 35000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Negro Estrella',
    ubicacion: 'Bogotá - Puente Aranda',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Renault Koleos espaciosa y confortable. Tracción 4x4 disponible, asientos en cuero, techo panorámico, sistema R-Link.',
    soat: true,
    tecnicomecanica: true,
    impuestos: false,
    dias_inventario: 30,
  },
  {
    id: 12,
    marca: 'Hyundai',
    modelo: 'Creta Premium',
    anio: 2024,
    precio: 105000000,
    precio_compra: 91000000,
    kilometraje: 6800,
    transmision: 'Automática',
    combustible: 'Gasolina',
    tipo: 'SUV',
    color: 'Azul Phantom',
    ubicacion: 'Bogotá - Niza',
    estado: 'Disponible',
    imagen: '/placeholder-car.jpg',
    descripcion: 'Hyundai Creta nueva generación, versión Premium. Diseño moderno, pantalla flotante, sistema BlueLink, asistente de estacionamiento.',
    soat: true,
    tecnicomecanica: true,
    impuestos: true,
    dias_inventario: 4,
  },
];

export const marcas = [
  'Toyota', 'Mazda', 'Chevrolet', 'Kia', 'Renault',
  'Hyundai', 'Nissan', 'Ford', 'Volkswagen', 'Suzuki',
];

export const tiposVehiculo = ['SUV', 'Sedán', 'Hatchback', 'Pickup', 'Camioneta', 'Van'];

export const transmisiones = ['Automática', 'Manual'];

export const combustibles = ['Gasolina', 'Diésel', 'Híbrido', 'Eléctrico'];

export function formatCOP(value: number): string {
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

export function formatNumber(value: number): string {
  return new Intl.NumberFormat('es-CO').format(value);
}
